name: iOS Build

# Ce workflow peut être exécuté manuellement ou déclenché automatiquement après une release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version à utiliser pour la build (ex: 1.2.3)"
        required: true
        default: ""
  # Ajout du déclencheur pour les nouvelles releases
  release:
    types: [published]

# Définition des permissions nécessaires
permissions:
  contents: write

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"

      - name: Display Flutter & Dart versions
        run: |
          flutter --version
          dart --version

      - name: Ajuster les dépendances pour la compatibilité
        run: |
          # Sauvegarder le pubspec.yaml original
          cp pubspec.yaml pubspec.yaml.bak
          
          # Méthode compatible avec macOS pour modifier pubspec.yaml
          echo "Modification des dépendances pour la compatibilité avec Flutter 3.19.0..."
          
          # Utiliser awk qui est plus compatible entre les systèmes
          cat pubspec.yaml | awk '
            /^  flutter_lints:/ { print "  flutter_lints: ^2.0.0"; next }
            /^  cupertino_icons:/ { print "  cupertino_icons: ^1.0.2"; next }
            /^  uuid:/ { print "  uuid: ^3.0.7"; next }
            /^  provider:/ { print "  provider: ^6.0.5"; next }
            /^  flutter_launcher_icons:/ { print "  flutter_launcher_icons: ^0.13.1"; next }
            { print }
          ' > pubspec.yaml.new
          
          if [ -f "pubspec.yaml.new" ]; then
            mv pubspec.yaml.new pubspec.yaml
            echo "Dépendances mises à jour avec succès."
            echo "Contenu du pubspec.yaml mis à jour:"
            cat pubspec.yaml
          else
            echo "ERREUR: La modification du pubspec.yaml a échoué."
            exit 1
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Set version
        id: set_version
        run: |
          # Si déclenché par une release, extraire la version du tag
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
            echo "Événement de release détecté, version extraite: $VERSION"
          else
            # Si déclenché manuellement, utiliser la version fournie
            VERSION="${{ github.event.inputs.version }}"
            echo "Événement manuel détecté, version utilisée: $VERSION"
          fi
          
          # Si la version est vide, extraire de pubspec.yaml
          if [ -z "$VERSION" ]; then
            if [ -f "pubspec.yaml" ]; then
              VERSION=$(grep -m 1 "version:" pubspec.yaml | awk '{print $2}' | tr -d '"'"'" | cut -d '+' -f1)
            fi
            
            # Si toujours vide, utiliser une valeur par défaut
            if [ -z "$VERSION" ]; then
              VERSION="1.0.0"
              echo "Aucune version détectée, utilisation de la valeur par défaut: $VERSION"
            fi
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version finale utilisée: $VERSION"

      - name: Build iOS Archive
        run: |
          echo "Construction de l'archive iOS pour la version ${{ steps.set_version.outputs.version }}..."
          
          # Mise à jour de CocoaPods
          cd ios && pod repo update && cd ..
          
          # Préparation de l'environnement Xcode
          flutter build ios --release --no-codesign
          
          # Vérification du chemin du build
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            echo "Répertoire Runner.app trouvé dans build/ios/iphoneos/"
          else
            echo "Recherche du chemin du Runner.app..."
            find build -name "Runner.app" -type d
          fi
          
          # Création d'un IPA sans signature
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          mkdir -p release-assets
          zip -r release-assets/foodguess-${{ steps.set_version.outputs.version }}-unsigned.ipa Payload
          rm -rf Payload

      # Utilisation de la version v4 de upload-artifact
      - name: Upload iOS build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: release-assets/*.ipa

      # Gérer les releases en fonction du type d'événement
      - name: Create/Update Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.set_version.outputs.version }}
          name: iOS Release v${{ steps.set_version.outputs.version }}
          body: |
            # Build iOS FoodGuess v${{ steps.set_version.outputs.version }}

            Cette version iOS a été compilée automatiquement sur un runner macOS.

            ## Téléchargements
            - [📱 Application iOS (non signée)](https://github.com/${{ github.repository }}/releases/download/v${{ steps.set_version.outputs.version }}/foodguess-${{ steps.set_version.outputs.version }}-unsigned.ipa)

            ## Notes
            Cette build n'est pas signée et ne peut pas être installée directement sur des appareils iOS.
            Pour installer l'application, vous devez la signer avec votre propre certificat de développeur.

            ## Informations techniques
            - Date de construction: ${{ github.event.repository.updated_at }}
            - Flutter: 3.19.0 (stable)
            - Version: ${{ steps.set_version.outputs.version }}
          files: |
            release-assets/*.ipa
          draft: false
          prerelease: false
