name: iOS Build

# Ce workflow est conçu pour être exécuté manuellement lorsqu'une build iOS est nécessaire

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version à utiliser pour la build (ex: 1.2.3)"
        required: true
        default: ""

# Définition des permissions nécessaires
permissions:
  contents: write

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"

      - name: Display Flutter & Dart versions
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS Archive
        run: |
          echo "Construction de l'archive iOS..."
          # Préparation de l'environnement Xcode
          flutter build ios --release --no-codesign

          # Création d'un IPA sans signature
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          mkdir -p release-assets
          zip -r release-assets/foodguess-${{ github.event.inputs.version }}-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload iOS build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: release-assets/*.ipa

      # Option: Créer une release GitHub si nécessaire
      - name: Create/Update Release
        if: ${{ github.event.inputs.version != '' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: iOS Release v${{ github.event.inputs.version }}
          files: |
            release-assets/*.ipa
          draft: false
          prerelease: false
